---
version: "3.3"
services:
  epic-server:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: epic-server
    image: "blastbeng/epic-server:1.0.0"
    restart: always
    ports:
      - "3413:3413"
      - "3414:3414"
      - "3415:3415"
      - "3416:3416"
    volumes:
      - "./chain_data:/home/epicuser/.epic/main/chain_data"
    entrypoint: ./entrypoint.sh